name:MLops CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.14'
      
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push FastAPI image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: meghasep26/fastapi:dev

      - name: Build and push Streamlit image
        uses: docker/build-push-action@v2
        with:
          context: ./streamlit_app
          file: ./streamlit_app/Dockerfile
          push: true
          tags: meghasep26/streamlit:dev